name: 'render-wsq'
description: 'Render web sequence diagrams to images'
author: 'Michael Holtzman @ Trepp'
inputs:
  folder:
    required: true
    description: Folder to search for wsq files for input
  style:
    required: false
    description: Style to use
    default: default
  commitChanges:
    required: false
    description: bool to indicate if action should commit changes automatically
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
